apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-test-app
  labels:
    app: scale-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-test-app
  template:
    metadata:
      labels:
        app: scale-test-app
    spec:
      containers:
      - name: scale-test-app-container
        image: shestera/scaletestapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "30Mi"
            cpu: "100m"
          limits:
            memory: "30Mi"
            cpu: "200m"
